workflows:
  ios_ipa_unsigned:
    name: iOS • Unsigned IPA
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter dependencies
        script: |
          flutter --version
          flutter pub get

      - name: Clean (fresh build)
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock

      - name: Build unsigned IPA
        script: |
          # يبني ipa بدون كود ساين
          flutter build ipa --release --no-codesign
          echo "== Listing build/ios/ipa =="
          ls -lah build/ios/ipa || true

      - name: Verify artifact
        script: |
          if [ ! -f "build/ios/ipa/Runner.ipa" ]; then
            echo "❌ IPA not found at build/ios/ipa/Runner.ipa"
            exit 1
          fi
          echo "✅ IPA ready: build/ios/ipa/Runner.ipa"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      # (اختياري) يصلك لينك التحميل على الإيميل
      email:
        recipients:
          - ahmedjackson47@gmail.com
