workflows:
  ios_unsigned_ipa:
    name: iOS unsigned IPA
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: 1.16.2
      vars:
        BUILD_NAME: "1.0.0"
        BUILD_NUMBER: "1"
        FLUTTER_ROOT: "/Users/builder/programs/flutter"

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true

    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.cocoapods
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods

    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter --version
          flutter clean
          flutter pub get

      - name: CocoaPods repo update & clean install
        script: |
          cd ios
          pod repo update
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Build iOS (no codesign)
        script: |
          # نبني أرشيف Device (يولّد Runner.app مع flutter_assets)
          flutter build ios --release --no-codesign \
            --build-name="${BUILD_NAME}" \
            --build-number="${BUILD_NUMBER}"

      - name: Verify Flutter assets exist
        script: |
          APP_DIR="build/ios/iphoneos/Runner.app"
          test -d "$APP_DIR" || { echo "❌ Runner.app غير موجود"; exit 64; }
          test -d "$APP_DIR/Frameworks/App.framework" || { echo "❌ App.framework مفقود"; exit 65; }
          test -d "$APP_DIR/flutter_assets" || { 
            echo "❌ مجلد flutter_assets مفقود (سبب شاشة سوداء)";
            ls -la "$APP_DIR";
            exit 66;
          }
          echo "✅ App.framework و flutter_assets موجودان"

      - name: Package unsigned IPA manually
        script: |
          set -e
          OUT="build/ios/ipa"
          mkdir -p "$OUT/Payload"
          cp -R "build/ios/iphoneos/Runner.app" "$OUT/Payload/Runner.app"
          (cd "$OUT" && zip -qry Runner.ipa Payload)
          echo "✅ IPA: $OUT/Runner.ipa"

    artifacts:
      - build/ios/ipa/Runner.ipa
