workflows:
  ios_unsigned:
    name: iOS Unsigned (PlaToN Sport)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter --version
          flutter clean
          flutter pub get

      - name: Reset CocoaPods (fresh pods after Podfile change)
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ..

      - name: Build iOS unsigned IPA (no codesign)
        script: |
          # تأكد أن ios/Runner/GoogleService-Info.plist موجود إن كنت تستخدم Firebase
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    # اختياري: شغّل فقط عند الدفع على الفرع main
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
