workflows:
  ios_unsigned_ipa:
    name: iOS unsigned IPA
    environment:
      flutter: stable
      xcode: latest
      vars:
        CM_CLONE_DIR: $CM_BUILD_DIR
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true

    scripts:
      - name: Show versions
        script: |
          flutter --version
          ruby --version
          gem --version
          which flutter

      - name: Install CocoaPods 1.16.2
        script: |
          gem install cocoapods -v 1.16.2 --no-document
          pod --version

      - name: Prepare Flutter iOS (precache + simulator build to generate ios/Flutter/podhelper.rb)
        script: |
          set -e
          flutter clean
          flutter pub get
          flutter precache --ios
          # توليد ملفات Flutter داخل ios/Flutter
          flutter build ios --simulator

      - name: CocoaPods repo update & install
        script: |
          set -e
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --verbose
          cd ..

      - name: Build iOS (no codesign)
        script: |
          set -e
          # أرشفة عبر Flutter (بدون توقيع)
          flutter build ipa --no-codesign

      - name: Verify IPA
        script: |
          set -e
          echo "== List build/ios/ipa =="
          ls -lah build/ios/ipa || true
          if [ -f "build/ios/ipa/Runner.ipa" ]; then
            echo "✅ IPA ready: build/ios/ipa/Runner.ipa"
          else
            echo "❌ IPA not found"
            exit 1
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      email:
        recipients:
          - "ahmedjackson47@gmail.com"
