workflows:
  ios_unsigned_ipa:
    name: iOS • Unsigned IPA (no codesign)
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - /Users/builder/Library/Caches/CocoaPods
    scripts:
      - name: Prep
        script: |
          flutter --version
          dart --version
          flutter clean
          flutter pub get
      - name: (optional) Pod install
        script: |
          cd ios
          pod repo update
          pod install
          cd ..
      - name: Build IPA (no codesign)
        script: |
          flutter build ipa --release --no-codesign
          echo "== IPA =="
          ls -lah build/ios/ipa || true
    artifacts:
      - build/ios/ipa/*.ipa
