workflows:
  ios_unsigned_ipa:
    name: iOS unsigned IPA
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.platonSport"   # عدّلها لو عندك Bundle Id مختلف
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter --version
          flutter clean
          flutter pub get
      - name: Precache iOS artifacts
        script: |
          flutter precache --ios
      # ⚠️ لا نعمل pod install يدوياً. اتركها لـ flutter build
      - name: Build iOS (no codesign)
        script: |
          # يولّد ios/Flutter/Generated.xcconfig (ضروري للـ Podfile أعلاه)
          flutter build ios --release --no-codesign
      - name: Verify Flutter assets exist
        script: |
          APP_DIR="build/ios/iphoneos/Runner.app"
          test -d "$APP_DIR" || { echo "❌ Runner.app غير موجود"; exit 64; }
          test -d "$APP_DIR/Frameworks/App.framework" || { echo "❌ App.framework مفقود"; exit 65; }
          test -d "$APP_DIR/flutter_assets" || { echo "❌ flutter_assets مفقود"; exit 66; }
          echo "✅ App.framework و flutter_assets موجودان"
      - name: Create unsigned IPA
        script: |
          set -e
          rm -rf Payload
          mkdir -p Payload
          cp -R build/ios/iphoneos/Runner.app Payload/
          cd Payload && zip -qry ../Runner.ipa . && cd ..
          ls -lah Runner.ipa
    artifacts:
      - Runner.ipa
