- name: Make unsigned IPA manually (no codesign)
  script: |
    set -e

    # ابحث عن الأرشيف الذي بنيناه في الخطوة السابقة
    ARCHIVE_PATH="$(find build -type d -name 'Runner.xcarchive' -maxdepth 6 -print | head -n 1)"
    if [ -z "$ARCHIVE_PATH" ]; then
      echo "❌ لم يتم العثور على Runner.xcarchive تحت build/"
      ls -lah build || true
      exit 65
    fi
    echo "✅ Found archive: $ARCHIVE_PATH"

    APP_PATH="$ARCHIVE_PATH/Products/Applications/Runner.app"
    if [ ! -d "$APP_PATH" ]; then
      echo "❌ لم يتم العثور على Runner.app داخل الأرشيف"
      find "$ARCHIVE_PATH" -maxdepth 4 -print
      exit 66
    fi

    # حضّر مجلد الإخراج
    OUT_DIR="build/ios/ipa"
    rm -rf "$OUT_DIR"
    mkdir -p "$OUT_DIR"

    # أنشئ Payload وضع داخله .app
    WORK_DIR="$(mktemp -d)"
    mkdir -p "$WORK_DIR/Payload"
    cp -R "$APP_PATH" "$WORK_DIR/Payload/Runner.app"

    # (اختياري) أضف dSYMs في zip منفصل كأثر بنائي
    if [ -d "$ARCHIVE_PATH/dSYMs" ]; then
      (cd "$ARCHIVE_PATH/dSYMs" && zip -r "$PWD/$OUT_DIR/Runner-dSYMs.zip" .)
    fi

    # أنشئ ملف IPA (هو مجرد zip باسم .ipa)
    (cd "$WORK_DIR" && zip -r "$PWD/$OUT_DIR/PlaToN_Sport-unsigned.ipa" Payload)

    echo "== IPA contents =="
    ls -lah "$OUT_DIR"
