workflows:
  ios_unsigned_ipa:
    name: iOS Unsigned (PlaToN Sport)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter clean & pub get
        script: |
          set -e
          flutter clean
          flutter pub get

      - name: Update CocoaPods repos & install
        script: |
          set -e
          cd ios
          pod repo update
          pod install --repo-update
          cd -

      - name: Build iOS (no codesign)
        script: |
          set -e
          flutter build ios --release --no-codesign

      - name: Ensure flutter_assets in .app (fix black screen)
        script: |
          set -e
          APP_DIR="build/ios/iphoneos/Runner.app"
          test -d "$APP_DIR" || { echo "❌ Runner.app غير موجود"; exit 64; }

          # انقل flutter_assets من داخل App.framework إن لزم
          if [ -d "$APP_DIR/Frameworks/App.framework/flutter_assets" ] && [ ! -d "$APP_DIR/flutter_assets" ]; then
            mv "$APP_DIR/Frameworks/App.framework/flutter_assets" "$APP_DIR/"
          fi

          # انسخ GoogleService-Info.plist إن وجد
          if [ -f "ios/Runner/GoogleService-Info.plist" ] && [ ! -f "$APP_DIR/GoogleService-Info.plist" ]; then
            cp ios/Runner/GoogleService-Info.plist "$APP_DIR/GoogleService-Info.plist"
          fi

          # تحقق نهائي (منع شاشة سوداء)
          test -f "$APP_DIR/Frameworks/App.framework/App" || { echo "❌ App.framework/App مفقود"; exit 65; }
          test -d "$APP_DIR/flutter_assets" || { echo "❌ flutter_assets مفقود (سبب شاشة سوداء)"; exit 66; }
          echo "✅ App.framework و flutter_assets موجودان"

      - name: Package unsigned IPA
        script: |
          set -e
          APP_DIR="build/ios/iphoneos/Runner.app"
          OUT_DIR="build/ios/ipa"
          mkdir -p "$OUT_DIR/Payload"
          cp -R "$APP_DIR" "$OUT_DIR/Payload/Runner.app"
          (cd "$OUT_DIR" && zip -qry "Runner-unsigned.ipa" Payload)
          rm -rf "$OUT_DIR/Payload"
          ls -lah "$OUT_DIR"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/Runner.app/**
      
