workflows:
  ios_unsigned_ipa:
    name: iOS Unsigned IPA
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - build/.dart_tool

    scripts:
      - name: Clean everything
        script: |
          set -e
          flutter --version
          xcodebuild -version
          pod --version
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/.symlinks || true
          rm -rf build

      - name: Get packages & precache iOS
        script: |
          set -e
          flutter pub get
          flutter precache --ios

      - name: Ensure Podfile exists
        script: |
          set -e
          test -f ios/Podfile || { echo "❌ ios/Podfile missing"; exit 1; }
          echo "✅ Podfile found"

      - name: CocoaPods repo update & install
        script: |
          set -e
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build iOS (no codesign)
        script: |
          set -e
          # تأكد أن Info.plist و Runner موجودين
          test -f ios/Runner/Info.plist || { echo "❌ ios/Runner/Info.plist missing"; exit 1; }
          # إبني IPA (Flutter سيستدعي xcodebuild archive داخلًا)
          flutter build ipa --release --no-codesign

      - name: Verify IPA & assets
        script: |
          set -e
          echo "== IPA files =="
          find build/ios -maxdepth 3 -name "*.ipa" -print || true
          test -f build/ios/ipa/Runner.ipa || { echo "❌ IPA not found"; exit 1; }
          echo "✅ IPA ready: build/ios/ipa/Runner.ipa"
          echo "== Check flutter assets =="
          APP="build/ios/iphoneos/Runner.app"
          if [ -d "$APP" ]; then
            test -d "$APP/Frameworks/App.framework" || { echo "❌ App.framework missing"; exit 66; }
            test -d "$APP/flutter_assets" || { echo "❌ flutter_assets missing"; exit 66; }
            echo "✅ App.framework & flutter_assets exist"
          else
            echo "ℹ️ Runner.app was cleaned by build; skipping assets check"
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
