workflows:
  ios_unsigned:
    name: iOS Unsigned (PlaToN Sport)
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable         # يستخدم أحدث قناة مستقرة من Flutter
      xcode: 15.4             # إصدار Xcode
      cocoapods: default
      vars:
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
        COCOAPODS_DISABLE_STATS: "true"

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods

    scripts:
      - name: Show versions
        script: |
          flutter --version
          pod --version
          xcodebuild -version

      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      - name: Reset CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ..

      - name: Build iOS unsigned IPA
        script: |
          # يبني IPA بدون توقيع (مناسب للجيلبريك/التوقيع اليدوي)
          BUILD_NUMBER=${CM_BUILD_ID:-1}
          flutter build ipa --release --no-codesign \
            --build-name=1.0.0 --build-number=$BUILD_NUMBER

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - ios/Podfile.lock

    publishing:
      email:
        recipients:
          - ${CM_EMAIL}
        notify:
          success: true
          failure: true
