workflows:
  ios_unsigned:
    name: iOS Unsigned (PlaToN Sport)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.platonSport"

    scripts:
      - name: Versions
        script: |
          flutter --version
          xcodebuild -version
          pod --version

      - name: Flutter clean & pub get
        script: |
          set -e
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
          flutter pub get

      - name: Ensure iOS dir
        script: |
          if [ ! -d "ios" ]; then
            flutter create .
          fi

      - name: Ensure GoogleService-Info.plist
        script: |
          set -e
          if [ -n "$CM_GSI_BASE64" ]; then
            echo "$CM_GSI_BASE64" | base64 --decode > ios/Runner/GoogleService-Info.plist
          fi
          if [ -f ios/Runner/GoogleService-Info.plist ]; then
            echo "OK: GoogleService-Info.plist present"
          else
            echo "WARN: GoogleService-Info.plist missing"
          fi

      - name: Pod install (fresh)
        script: |
          set -e
          cd ios
          if ! grep -q "use_frameworks!" Podfile; then
            echo "use_frameworks! :linkage => :static" | cat - Podfile > /tmp/out && mv /tmp/out Podfile
          fi
          if ! grep -q "use_modular_headers!" Podfile; then
            echo "use_modular_headers!" | cat - Podfile > /tmp/out && mv /tmp/out Podfile
          fi
          pod repo update
          pod install
          cd ..

      # يبني Runner.xcarchive (نفس اللي ظهر عندك)
      - name: Build archive with Flutter (no codesign)
        script: |
          set -e
          flutter build ios --release --no-codesign

      # هنا الخطوة التي كانت ناقصة: تصدير IPA من الأرشيف
      - name: Export unsigned IPA from archive
        script: |
          set -e
          mkdir -p build/ios/ipa
          cat > /tmp/ExportOptions.plist <<'PLIST'
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>compileBitcode</key><false/>
            <key>destination</key><string>export</string>
            <key>method</key><string>ad-hoc</string>
            <key>signingStyle</key><string>manual</string>
            <key>stripSwiftSymbols</key><false/>
            <key>thinning</key><string>&lt;none&gt;</string>
            <key>manageAppVersionAndBuildNumber</key><false/>
          </dict>
          </plist>
          PLIST

          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist /tmp/ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY=""

          echo "== IPA contents =="
          ls -lah build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      email:
        recipients:
          - YOUR_EMAIL@EXAMPLE.COM
