workflows:
  ios_unsigned_ipa:
    name: iOS Unsigned IPA
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.cocoapods
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - build/.dart_tool

    scripts:
      - name: Clean & show versions
        script: |
          set -e
          flutter --version
          xcodebuild -version
          pod --version
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/.symlinks || true

      - name: Get packages & precache iOS
        script: |
          set -e
          flutter pub get
          flutter precache --ios

      - name: Ensure Podfile exists
        script: |
          set -e
          test -f ios/Podfile || { echo "❌ ios/Podfile missing"; exit 1; }

      - name: CocoaPods repo update & install
        script: |
          set -e
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build iOS (no codesign)
        script: |
          set -e
          flutter build ipa --release --no-codesign

      - name: Verify IPA
        script: |
          set -e
          find build/ios -maxdepth 3 -name "*.ipa" -print
          test -f build/ios/ipa/Runner.ipa || { echo "❌ IPA not found"; exit 1; }
          echo "✅ IPA ready: build/ios/ipa/Runner.ipa"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
