workflows:
  ios_unsigned_ipa:
    name: iOS unsigned IPA
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter clean & deps
        script: |
          flutter --version
          flutter clean
          flutter pub get
          flutter precache --ios
      # تحديث مستودعات CocoaPods فقط (بدون pod install)
      - name: Update CocoaPods specs
        script: |
          cd ios
          pod repo update
          cd ..
      # البناء بدون توقيع — Flutter سيجري pod install بالطريقة الصحيحة ويولد Generated.xcconfig
      - name: Build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign
      # تأكيد وجود الأصول (سبب الشاشة السوداء غالباً نقص flutter_assets)
      - name: Verify Flutter assets exist
        script: |
          APP_DIR="build/ios/iphoneos/Runner.app"
          test -d "$APP_DIR" || { echo "❌ Runner.app غير موجود"; exit 64; }
          test -d "$APP_DIR/Frameworks/App.framework" || { echo "❌ App.framework مفقود"; exit 65; }
          test -d "$APP_DIR/flutter_assets" || { echo "❌ flutter_assets مفقود"; exit 66; }
          echo "✅ App.framework و flutter_assets موجودان"
      # تجميع IPA غير موقّع
      - name: Make unsigned IPA
        script: |
          set -e
          rm -rf Payload Runner.ipa
          mkdir -p Payload
          cp -R build/ios/iphoneos/Runner.app Payload/
          zip -qry Runner.ipa Payload
          ls -lah Runner.ipa
    artifacts:
      - Runner.ipa
