# codemagic.yaml — كامل وجاهز
workflows:
  ios_unsigned_ipa:
    name: iOS Unsigned IPA
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        IOS_MIN_VER: "15.0"
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.cocoapods
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - build/.dart_tool
    scripts:
      - name: Show tools versions & clean
        script: |
          set -e
          flutter --version
          dart --version || true
          xcodebuild -version
          pod --version
          echo "FLUTTER_ROOT=$FLUTTER_ROOT"
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/.symlinks || true

      - name: Get packages & precache iOS
        script: |
          set -e
          flutter pub get
          flutter precache --ios

      - name: Write a correct ios/Podfile (uses FLUTTER_ROOT)
        script: |
          set -e
          cat > ios/Podfile <<'POD'
          platform :ios, '15.0'
          use_frameworks! :linkage => :static
          use_modular_headers!
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          project 'Runner', {
            'Debug' => :debug,
            'Profile' => :release,
            'Release' => :release,
          }

          # حمّل podhelper.rb من Flutter SDK عبر متغير البيئة FLUTTER_ROOT
          flutter_root = ENV['FLUTTER_ROOT']
          if flutter_root.nil? || flutter_root.empty?
            abort "❌ FLUTTER_ROOT is not set by Flutter tool"
          end
          load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

          target 'Runner' do
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

            # إصلاحات static + module maps لبعض تبعيات Firebase
            pod 'GoogleUtilities', '7.13.1', :modular_headers => true
          end

          post_install do |installer|
            installer.pods_project.targets.each do |t|
              t.build_configurations.each do |config|
                config.build_settings['ENABLE_BITCODE'] = 'NO'
                config.build_settings['SWIFT_VERSION'] = '5.0'
                config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
                config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -framework Flutter'
              end

              if t.name == 'gRPC-C++' || t.name == 'gRPC-Core'
                t.build_configurations.each do |config|
                  config.build_settings['MACH_O_TYPE'] = 'staticlib'
                end
              end
            end
          end
          POD
          echo "✅ Wrote ios/Podfile"

      - name: CocoaPods repo update & install
        script: |
          set -e
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build unsigned IPA (no codesign)
        script: |
          set -e
          # تأكد من أن الـ Info.plist و Version مضبوطين من pubspec.yaml
          flutter build ipa --release --no-codesign

      - name: Verify IPA & list outputs
        script: |
          set -e
          echo "== Tree build/ios =="
          find build/ios -maxdepth 3 -print | sed 's/^/  /'
          if [ -f "build/ios/ipa/Runner.ipa" ]; then
            echo "✅ IPA ready: build/ios/ipa/Runner.ipa"
          else
            echo "❌ IPA not found, searching..."
            find build -maxdepth 5 -type f -name "*.ipa" -print
            exit 1
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      email:
        recipients:
          - ahmedjackson47@gmail.com
        notify:
          success: true
          failure: true
