workflows:
  ios_unsigned:
    name: iOS Unsigned (PlaToN Sport)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods
    scripts:
      # معلومات سريعة مفيدة في اللوج
      - name: Flutter doctor
        script: |
          flutter --version
          flutter doctor -v

      # لو مجلد ios غير موجود (أحيانًا محذوف من المستودع)، يتم إنشاؤه
      - name: Ensure ios directory exists (first time only)
        script: |
          if [ ! -d "ios" ]; then
            echo "No ios/ folder, running: flutter create ."
            flutter create .
          fi

      # تنظيف قوي + جلب الحزم
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      # إعادة تهيئة CocoaPods (مهم بعد أي تعديل على Podfile)
      - name: Reset CocoaPods (fresh pods after Podfile change)
        script: |
          set -e
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          cd ..

      # بناء الأرشيف بدون توقيع (Flutter سيُنتج Runner.xcarchive)
      - name: Build iOS unsigned IPA (no codesign)
        script: |
          set -e
          # ارفع الهدف الأدنى إن احتجت (يتم ضبطه تلقائيًا غالبًا)
          flutter build ios --release --no-codesign
          echo "== Find any xcarchive produced by Flutter =="
          # اطبع أي أرشيف تم توليده لنتأكد من المسار
          find build -type d -name "*.xcarchive" -maxdepth 6 -print || true

      # تصدير IPA عبر xcodebuild مع اكتشاف مسار الأرشيف ديناميكيًا
      - name: Export unsigned IPA from archive
        script: |
          set -e
          ARCHIVE_PATH="$(find build -type d -name 'Runner.xcarchive' -maxdepth 6 -print | head -n 1)"
          if [ -z "$ARCHIVE_PATH" ]; then
            echo "❌ لم يتم العثور على Runner.xcarchive تحت build/"
            echo "محتويات build/:"
            ls -lah build || true
            exit 65
          fi
          echo "✅ Found archive at: $ARCHIVE_PATH"

          mkdir -p build/ios/ipa
          cat > /tmp/ExportOptions.plist <<'PLIST'
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>compileBitcode</key><false/>
            <key>destination</key><string>export</string>
            <key>method</key><string>ad-hoc</string>
            <key>signingStyle</key><string>manual</string>
            <key>stripSwiftSymbols</key><false/>
            <key>thinning</key><string>&lt;none&gt;</string>
            <key>manageAppVersionAndBuildNumber</key><false/>
          </dict>
          </plist>
          PLIST

          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath build/ios/ipa \
            -exportOptionsPlist /tmp/ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY=""

          echo "== IPA contents =="
          ls -lah build/ios/ipa || true
          # في الغالب سيكون الاسم Runner.ipa
          if [ -f "build/ios/ipa/Runner.ipa" ]; then
            echo "✅ IPA ready: build/ios/ipa/Runner.ipa"
          fi
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
