workflows:
  ios_adhoc:
    name: iOS AdHoc (PlaToN Sport)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Build IPA (release)
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      email:
        recipients:
          - you@example.com
        notify:
          success: true
          failure: true
