workflows:
  ios_unsigned_ipa:
    name: iOS unsigned IPA (no codesign)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 15.4
      vars:
        IOS_MIN_VER: "15.0"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true

    scripts:
      - name: Show Flutter & clean
        script: |
          flutter --version
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
          flutter pub get

      # يكتب Podfile كامل (نفس الحل المقترح لتثبيت Firebase 10.x وتجنّب Swift 6)
      - name: Write Podfile (pin Firebase 10.x + Swift 5)
        script: |
          cat > ios/Podfile <<'POD'
          platform :ios, '15.0'
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          project 'Runner', {
            'Debug' => :debug,
            'Profile' => :release,
            'Release' => :release,
          }

          # اكتشاف FLUTTER_ROOT بشكل آمن
          flutter_root = ENV['FLUTTER_ROOT']
          if flutter_root.nil? || flutter_root.empty?
            begin
              machine = `flutter --version --machine 2>/dev/null`
              m = machine.match(/"flutterRoot"\s*:\s*"([^"]+)"/)
              flutter_root = m[1] unless m.nil?
            rescue
              flutter_root = nil
            end
          end
          if flutter_root.nil? || flutter_root.empty?
            which_flutter = `which flutter`.strip
            if !which_flutter.nil? && !which_flutter.empty?
              bin_dir = File.dirname(which_flutter)
              maybe_root = File.expand_path('..', bin_dir)
              candidate = File.join(maybe_root, 'flutter')
              flutter_root = candidate if File.exist?(candidate)
            end
          end
          raise 'FLUTTER_ROOT not resolved; cannot load podhelper.rb' if flutter_root.nil? || flutter_root.empty?
          load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

          use_frameworks! :linkage => :static
          use_modular_headers!

          # 🔒 تثبيت سلسلة Firebase iOS SDK على 10.x (Swift 5)
          $FirebaseVersion = '10.25.0'

          flutter_ios_podfile_setup

          target 'Runner' do
            # Pods الخاصة بفلاتر
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

            # 🔒 إجبار Firebase على 10.25.0 لتفادي مشاكل Swift 6
            pod 'Firebase/Core', $FirebaseVersion
            pod 'FirebaseCore', $FirebaseVersion
            pod 'FirebaseCoreInternal', $FirebaseVersion
            pod 'FirebaseFirestore', $FirebaseVersion
            pod 'FirebaseFirestoreInternal', $FirebaseVersion
            pod 'GoogleUtilities', '7.13.1'
            pod 'nanopb', '2.30910.0'
          end

          post_install do |installer|
            installer.pods_project.targets.each do |t|
              flutter_additional_ios_build_settings(t)
              t.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
                config.build_settings['SWIFT_VERSION'] = '5.0'
                config.build_settings['ENABLE_BITCODE'] = 'NO'

                flags = config.build_settings['OTHER_SWIFT_FLAGS']
                if flags.is_a?(String)
                  cleaned = flags.split(' ').reject { |f|
                    f.include?('enable-upcoming-feature') || f.include?('enable-experimental-feature') || f.include?('swift-version')
                  }.join(' ')
                  config.build_settings['OTHER_SWIFT_FLAGS'] = cleaned
                end
                config.build_settings['SWIFT_ENABLE_EXPERIMENTAL_FEATURES'] = ''
              end
            end
          end
          POD

      - name: Ensure GoogleService-Info.plist exists
        script: |
          if [ ! -f "ios/Runner/GoogleService-Info.plist" ]; then
            echo "❌ ios/Runner/GoogleService-Info.plist غير موجود. نزّله من Firebase Console وضعه هنا."
            ls -lah ios/Runner || true
            exit 1
          fi

      - name: CocoaPods install
        script: |
          cd ios
          pod repo update
          pod install --verbose
          cd -

      # بناء IPA بدون توقيع (Flutter يقوم بإنشاء الأرشيف والـ IPA)
      - name: Build unsigned IPA (no code signing)
        script: |
          # اختياري: تثبيت إصدارات FlutterFire المتوافقة في pubspec.yaml قبل هذا الخطوة
          # تأكد أنّك محدّد:
          #   firebase_core: 2.24.2
          #   cloud_firestore: 4.15.9
          flutter build ipa --release --no-codesign
          echo "== Contents =="
          find build/ios -maxdepth 3 -print

      - name: Verify artifact
        script: |
          if [ -f "build/ios/ipa/Runner.ipa" ]; then
            echo "✅ IPA ready: build/ios/ipa/Runner.ipa"
          else
            echo "❌ IPA not found, listing:"
            find build -maxdepth 4 -type f -name "*.ipa" -print
            exit 1
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      email:
        recipients:
          - "your@email.com"
        notify:
          success: true
          failure: true
