workflows:
  ios_unsigned:
    name: iOS Unsigned (PlaToN Sport)
    max_build_duration: 60
    environment:
      flutter: stable          # أو ثبّت رقمًا محددًا مثل 3.22.2
      xcode: latest            # أو 15.4
      cocoapods: default
      vars:
        APP_ID: "com.example.platonSport"  # طابق Bundle Identifier في Runner

    scripts:
      - name: Print tool versions
        script: |
          flutter --version
          xcodebuild -version
          pod --version

      - name: Flutter clean & pub get
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
          flutter pub get

      - name: Ensure iOS directory exists (first time only)
        script: |
          if [ ! -d "ios" ]; then
            flutter create .
          fi

      - name: Build iOS unsigned IPA (no codesign)
        script: |
          set -e
          flutter build ipa --release --no-codesign
          echo "== List build/ios/ipa =="
          ls -lah build/ios/ipa || true
          echo "== List build/ios/archive =="
          ls -lah build/ios/archive || true

    # ⚠️ هذا القسم يجب أن يكون على نفس مستوى scripts (وليس بداخلها)
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - build/ios/ipa/*.dSYM.zip
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - ahmedjackson47@gmail.COM
