workflows:
  ios_unsigned:
    name: iOS Unsigned (PlaToN Sport)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_ID: "com.example.platonSport"   # تأكد يطابق Bundle Identifier في Runner
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter --version
          flutter clean
          flutter pub get

      - name: Ensure iOS directory exists (first time only)
        script: |
          if [ ! -d "ios" ]; then
            flutter create .
          fi

      # ✅ هذا هو الأهم: بناء IPA الرسمي الذي يضع App.framework + flutter_assets تلقائياً
      - name: Build iOS unsigned IPA (no codesign)
        script: |
          flutter build ipa --release --no-codesign \
            --dart-define=FLUTTER_WEB_USE_SKIA=false \
            --split-debug-info=build/ios/debug-info

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/debug-info/**

    publishing:
      email:
        recipients:
          - ahmedjackson47@gmail.com
