platform :ios, '13.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# يلتقط مسار Flutter SDK بشكل صحيح على أي CI (ومنها Codemagic)
flutter_root = File.dirname(`which flutter`)
flutter_root = File.expand_path('..', flutter_root)
load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

# مطلوبة لعدد من البودات (Firestore وغيره)
use_frameworks! :linkage => :static
use_modular_headers!

flutter_ios_podfile_setup

target 'Runner' do
  # ثبّت كل بودات Flutter/البلجنز
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # تعطيل bitcode والتوافق مع Swift/Pods
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
    end
  end
end
