// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDYHzp_p4mdqnKeptzGtE2idzBBlYa9mE',
    appId: '1:26767235930:web:85c4d6f948d5e6d0847163',
    messagingSenderId: '26767235930',
    projectId: 'platon-tv',
    authDomain: 'platon-tv.firebaseapp.com',
    storageBucket: 'platon-tv.firebasestorage.app',
    measurementId: 'G-9PF2R5JP5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7v27DMkST_3jwf8DDqWNiMe32t2FMoUg',
    appId: '1:26767235930:android:0fbc639637a78741847163',
    messagingSenderId: '26767235930',
    projectId: 'platon-tv',
    storageBucket: 'platon-tv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApcLfOeIdFBXw1cY31Fk7IP_6FuQSlLeY',
    appId: '1:26767235930:ios:d32379cea7e366c2847163',
    messagingSenderId: '26767235930',
    projectId: 'platon-tv',
    storageBucket: 'platon-tv.firebasestorage.app',
    iosBundleId: 'com.example.platonSport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApcLfOeIdFBXw1cY31Fk7IP_6FuQSlLeY',
    appId: '1:26767235930:ios:d32379cea7e366c2847163',
    messagingSenderId: '26767235930',
    projectId: 'platon-tv',
    storageBucket: 'platon-tv.firebasestorage.app',
    iosBundleId: 'com.example.platonSport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDYHzp_p4mdqnKeptzGtE2idzBBlYa9mE',
    appId: '1:26767235930:web:38fcffe0c30402ca847163',
    messagingSenderId: '26767235930',
    projectId: 'platon-tv',
    authDomain: 'platon-tv.firebaseapp.com',
    storageBucket: 'platon-tv.firebasestorage.app',
    measurementId: 'G-V7X7WDSNGZ',
  );

}